- layouts/partials/footer_custom.html
Adding EclipseCon Europe 2018.
> remove JAX 2018

- layouts/partials/sidebar.html
Clicking the 'Become a Member' link in the sidebar currently results in a 404. This PR fixes the link URL.
> Fixed 'Become a Member' link

- content/legal/acronym_guidelines/index.md
The only modifications of the document:
- Addition of the phrase "Supplement to the Eclipse Foundation Guidelines for Eclipse Logos & T\
rademarks Policy for Oracle/JCP Acronyms" as found in the Trademark Guidelines
- Reference turned into a hyperlink https://blogs.eclipse.org/post/mike-milinkovich/update-jakarta-ee-rights-java-trademarks
- Acronym list was sorted
> Acronym guidelines

- layouts/membership/section.html
Added button+copy content under the main header of membership page about
contacting Eclipse Fdn for joining Jakarta EE
Change-Id: I99018d0a9975afedc30920331085ca3ac4922943
> Adding the Jakarta EE & IoT contact us Button and Icon on the page #349

- content/about/jesp/index.md
This new revision was approved by the Jakarta EE Specification Committee
on July 15/2019, and then by the Jakarta EE Steering Committee on July
16/2019.
> Update to the 1.2 revision of the JESP

- content/about/jesp/index.md
There's some odd magic happening with the rendering of the date when using a slash to separate the day from the year, so I've changed it to a comma.
Signed-off-by: Wayne Beaton <wayne.beaton@eclipse-foundation.org>
> Use a comma instead of a slash in the data format

- layouts/specifications/list.html
We want visitors to the /specification directory to see a list containing the title and summary for each specification.
I've got a pull request against the specifications repository that adds _index.md to each of the directories under /specifications to provide the metadata that we need to show a title and summary.
> First attempt at list file for specifications.

- content/membership/members.md
Removed RCP Vision from members page.
Change-Id: Ic353efb40a1dbfd90c4bec9ef9044120b4049e82
> Remove RCP Vision from Jakarta EE webpage #361

- content/compatibility/get_listed/_index.md
Updated links available on the get listed page, as well as the title.
Added an ID to the header for How to get listed to link the jumbotron
button to.
Change-Id: Id984f23d4210d4aa7c05cdcdf91d796a81bf7791
> Developing the "Get Listed" page #388

- config.toml
Added config values for Youtube, Facebook, Twitter, and LinkedIn footer
links.
Change-Id: I0e7fd64d036ca16ea794ae7f58decea142e47756
> Update Social Media links in jakarta.ee footer #435

- content/membership/members.md
Removed cloudbees member page reference.
Change-Id: I48eaa6e98b2736f2e2858a2229db8e7d36dad7d7
> Remove Cloudbees from the Jakarta EE website #480

- data/compatible_products.yml
Removed v17 WebFly from Full profile, added v18 WebFly to both profiles.
Change-Id: Ice7cc45f41db68e32ce72a504114aa5d2b01048b
> Please include WildFly 18.0.0.Final as both Web Profile + Full... #508

- content/resources/_index.md
This is a first step towards #350. Note that the First Cup is still not Jakartized and CargoTracker is missing its original website (https://m-reza-rahman.github.io/cargo-tracker/) and its documentation (https://github.com/J3E/cargo-tracker-documentation). I thinks it's acceptable as this is a temporary link.
> Added documentation links

- config.toml
- content/_index.md
- content/about/_index.md
- content/about/jesp/index.md
- content/compatibility/_index.md
- content/compatibility/get_listed/_index.md
- content/connect/index.md
- content/legal/trademark_guidelines/index.md
- content/meeting_minutes/_index.md
- content/membership/_index.md
- content/newsletter/index.md
- content/release/_index.md
- content/resources/_index.md
- data/compatible_products.yml
- data/featuredstory.yml
Updated Jumbotron, titles, descriptions, and some data objects to have
TM marks for Jakarta references.
> Add ™ on jakarta.ee website #548

- content/about/_index.md
Replaced David Delabassee with Melissa Jacobus as Marketing Committee alternate.
Signed-off-by: Ed Bratt <ed.bratt@oracle.com>
> Updated Marketing Committee alternate for Oracle

- content/committees/specification/_index.md
> Fix typo in name of Specification Committee.

- data/events.yml
> Remove Devoxx UK 2020 (cancelled) from upcoming events

- content/committees/specification/operations/index.md
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>
The main point of this PR is to indicate that the second PR for housing just the Javadoc is optional.  The javadoc itself is still required, but it could be provided via the first PR instead of creating a second PR.  This modification to our process was agreed to at a recent Spec Committee meeting.
I also corrected the references to the various checklist templates.  We were missing one of the template references and I added some text to explain the use of the "review checklist".
And, just a couple of minor wordsmithing and formatting updates.
> Indicate the second PR is optional

- static/xml/ns/jakartaee/batchXML_2_0.xsd
- static/xml/ns/jakartaee/jobXML_2_0.xsd
Signed-off-by: Scott Kurz <skurz@us.ibm.com>
Following Jakarta EE 9 convention , have the "version" attribute for the top-level element ("job") match the spec version and file name... so bump up from 1.0 to 2.0.
The earlier PR #707 converted the target NS of the schema elements but it left the version as 1.0.
The matching PR in 'batch-api': eclipse-ee4j/batch-api#103 has been reviewed (unfortunately we have the files duplicated across the two projects, but changes should be rare).
One slightly less-elegant component of this fix is to define our own version type, as mentioned in the comment.  This avoids including the common Jakarta schema file which doesn't seem worth it for such a simple type definition.   Tried to avoid any namespace collision with the 'batchVersionType' name.
---
(We …
> Update batch XSDs to version 2.0

- data/compatible_products.yml
https://github.com/jakartaee/jakarta.ee/pull/856#issuecomment-681109524
This reverts commit 0d733aa1d462d30d475c5da8ada1804411897cab.
> Revert "Open Liberty 20.0.0.3 as a Compatible Software Product"

- content/committees/specification/_index.md
After referring to `Contributing `in `readme`, this should be to src. 
fix #883 
> add 2 members in commitee/specifications page

- config.toml
> fix documentation sub menu not showing under resources

- i18n/en.toml
- i18n/zh.toml
- layouts/partials/sidebar.html
Fix sidebar URLs to use absLangURL function rather than a broken
hardcoded prefix.
Fixes #927.
> Navigation sidebar contains broken links #927

- data/jakartaee_schemas.yml
- data/jaxb_schemas.yml
- data/jaxws_schemas.yml
- data/persistence_schemas.yml
Marking final for the following schemas:
- jakartaee_9
- jakartaee_web_services_metadata_handler_3_0
- batchXML_2_0
- jobXML_2_0
- jsp_3_0
- application_9
- application-client_9
- connector_2_0
- ejb-jar_4_0
- jakartaee_web_services_2_0
- jakartaee_web_services_client_2_0
- permissions_9
- web-app_5_0
- web-fragment_5_0
- web-common_5_0
- web-facesconfig_3_0
- web-facelettaglibrary_3_0
- web-partialresponse_3_0
- web-jsptaglibrary_3_0
- bindingschema_3_0
- wsdl_customizationschema_3_0
- orm_3_0
- persistence_3_0
> Update schemas to final for 9.0
