jakartaee/jakarta.ee

- content/news/community-news/itjungle-goodbye-java-enterprise-edition-hello-jakarta-ee/index.md
> Issue Add Community News Item #12

- README.md
- static/CONTRIBUTING.md
- static/README.md
> Update notice and readme

- config.toml
- content/connect/index.md
- content/news/community-news/infoworld-java-roadmap-eclipses-jakarta-ee-enterprise-java-takes-shape/index.md
- layouts/index.html
- package-lock.json
- package.json
- webpack.mix.js
> migrate to google tag

- content/news/announcements/jakarta_ee_at_eclipsecon_france_2018/index.md
> Add new announcement  for ECF2018

- content/news/announcements/jakarta_ee_progress_to_date/index.md
> Add new announcement about the Jakarta EE progress

- content/news/announcements/jakarta_ee_newsletter_a_first_look/index.md
- content/newsletter/index.md
- layouts/partials/sidebar.html
> Jakarta EE Newsletter #39

- content/news/community-news/enter-jakarta-ee-inoculation-against-fear-uncertainty-and-doubt-java-community/index.md
- content/news/community-news/java-blogs/index.md
- content/news/community-news/where-does-java-in-the-enterprise-go-from-here/index.md
> Add Community News items

- content/news/community-news/lightbend-podcast-why-lightbend-joined-the-eclipse-foundations/index.md
> Add Community News #45

- content/news/community-news/javaee7-javaee8-backward-compatibility/index.md
- content/news/community-news/proposed-jakarta-ee-design-principles/index.md
> #50 #51 - Update a community news and add a new one

- content/news/announcements/jakarta-ee-marketing-and-social-media-update/index.md
> Add a new annoucement

- layouts/partials/footer_custom.html
> Update the events section

- layouts/partials/footer_custom.html
> Add ECE3018 in list of events

- layouts/index.html
- layouts/partials/footer_custom.html
Take down EclipseCon France ad and swap for EclipseCon Europe ad #62
> Please add events button to bottom of Event section on homepage #63

- content/news/community-news/2018-07-13-jakarta-ee-eclipse-microprofile-and-cloud-native-eclipsecon-france/index.md
> Add a community news

- content/news/community-news/2018-07-24-jakarta-ee-no-turning-back/index.md
> Add a new community news

- content/meeting_minutes/index.md
> #75 - Add sections to the meeting minutes page

- layouts/partials/footer_custom.html
> Add view more items functionality to Events section

- layouts/partials/footer_custom.html
> Fix events layout and change more events button text

- layouts/partials/footer_custom.html
> Reorder events

- content/news/announcements/eclipse_foundation_announces_jakarta_ee_committee_election_results/index.md
> Add a new announcement

- content/news/announcements/eclipse_foundation_announces_jakarta_ee_committee_election_results/index.md
Stephanie Swart <stephanie.swart@eclipse-foundation.org>
> wrong name

- content/news/community-news/2018-07-27-understanding-jakarta-ee-series-eisele/index.md
- content/news/community-news/2018-07-30-jakarta-ee-vision/index.md
- content/news/community-news/2018-07-30-understanding-jakarta-ee-series-juneau/index.md
- content/news/community-news/2018-08-01-understanding-jakarta-ee-interview-keil/index.md
> Add new community news items

- layouts/partials/footer_custom.html
> #99 - Add new events

- layouts/partials/footer_custom.html
> Add new event to Voxxed Days event to footer

- layouts/partials/footer_custom.html
> Please add new Event #113

- layouts/partials/sidebar.html
Signed-off-by: Daniel Dias <daniel.dias.analistati@gmail.com>
add link to Technical Direction. #104
> link to Technical Direction.

- layouts/partials/footer_custom.html
> #116 - Add new event

- layouts/partials/footer_custom.html
> Update events in footer

- content/news/community-news/tomitribe-jnosql-and-jakarta-ee/index.md
https://www.tomitribe.com/blog/jnosql-and-jakarta-ee/ #127
> Please add to community news:

- content/news/announcements/2018-09-27-jakarta-ee-status-september-2018-update/index.md
> #136 - Add announcement for status of sept 2018

- content/news/announcements/2018-09-27-2018-java-ee-tck-now-open-sourced-eclipse-foundation/index.md
> #137 - Add new announcement for Java EE TCK

- content/about/faq/index.md
> Update FAQ's https://jakarta.ee/about/faq/ #134

- content/news/announcements/2018-10-16-jakarta-spec-process/index.md
- content/news/community-news/2018-10-17-draft-jakarta-ee-specification-process-live/index.md
> Please add items to news sections #146

- content/news/announcements/2018-10-25-announcing-eclipse-glassfish-510-rc1-release/index.md
> #154 - Add a new announcement

- content/news/announcements/2018-09-27-jakarta-ee-status-september-2018-update/index.md
> Fix link for Jakarta EE Status – September 2018 Update

- content/news/community-news/2018-11-08-jakarta-ee-spec-process-paves-way-for-enterprise-java/index.md
- content/news/community-news/2018-11-08-jakarta-ee-what-is-it-and-what-does-it-mean-for-enterprise-java/index.md
Please add to community news:
https://www.theserverside.com/news/252451430/Jakarta-EE-spec-process-paves-way-for-enterprise-Java
#158
> Please add community news item #157

- content/news/community-news/2018-12-13-eclipse-ee4j-and-glassfish-now-being-fully-built-and-tested-as-open-source/index.md
- layouts/partials/footer_custom.html
> #165 #166 - Add community news and new events

- content/legal/trademark_guidelines/index.md
- layouts/partials/sidebar.html
> Infra 3081 - Add the trademark guidelines

- content/about/faq/index.md
> Add GlassFish FAQ

- layouts/partials/footer_custom.html
> #180 -  Remove passed events

- config.toml
- content/connect/index.md
> Add Jakartablogs to the menu and the Stay Connected section

- content/news/community-news/2019-01-01-2018-annual-summary/index.md
- content/news/community-news/2019-01-21-eclipse-specification-process-iv-the-specification-committee-votes/index.md
- content/news/community-news/2019-01-22-jersey-has-been-released/index.md
- content/news/community-news/2019-01-26-eclipse-glassfish-has-been-released/index.md
- content/news/community-news/2019-01-29-eclipse-glassfish-5-1-is-here/index.md
- content/news/community-news/2019-01-29-eclipse-glassfish-5-1-is-released/index.md
- content/news/community-news/2019-01-29-jakarta-ee-milestone-eclipse-glassfish-51-is-java-ee-8-compatible/index.md
> Add new community news

- content/news/announcements/2019-01-28-eclipse-releases-glassfish-51-for-java-ee-8/index.md
- content/news/announcements/2019-01-29-jakartablogsee-live-ps-bloggers-we-need-you/index.md
> #183 - Add new announcements

- layouts/partials/footer_custom.html
> #180 - Add new events

- content/newsletter/index.md
> #188 - Add newsletter to archives page

- content/news/community-news/2019-01-30-eclipse-glassfish/index.md
> #189 - Add new community news item

- layouts/partials/footer_custom.html
> #201 - Update events section

- layouts/index.html
> Infra 3146 - Remove Vaddin from participating members

- content/news/announcements/2019-01-29-java-ee-8-compatible-eclipse-glassfish-5-1-released/index.md
> #206 - Add a new announcement

- package-lock.json
- package.json
> Update theme to 0.0.12

- content/about/index.md
> Improve the Jakarta EE working group page #118

- content/about/_index.md
> Fix FAQ page

- content/membership/_index.md
> Update contact form text blurb

- layouts/index.html
> #216 - Add featured-story block to home page

- content/membership/members.md
> Remove Vaadin from members list

- layouts/index.html
> Change the featured story link

- content/membership/_index.md
> Remove contact membership link

- content/news/announcements/2019-03-04-2019-jakarta-ee-developer-survey-underway/index.md
> Issue #221 - Add new announcement

- content/membership/members.md
> Bug 3177 - Remove Genuitec from the Jakarta website

- content/news/announcements/2019-03-18-2019-how-participate-advancing-jakarta-ee-specification/index.md
> #230 - Add new announcement

- layouts/index.html
> Fix the height of news items

- layouts/index.html
- layouts/partials/featured_story.html
> #233 - Remove featured story from home page

- layouts/index.html
> #235 - Remove passed events

- .travis.yml
- config.toml
- data/events.yml
- layouts/index.html
- package-lock.json
- package.json
> Improve how we update the events

- content/news/announcements/2019-03-26-2019-thank-you-taking-jakarta-ee-2019-developer-survey/index.md
> #243 - Add new announcement

- content/membership/members.md
> Add k-teq to the participating members

- content/news/announcements/2019-04-03-2019-how-participate-advancing-jakarta-ee-specification-technical-and-collateral/index.md
- content/news/announcements/2019-04-04-2019-renaming-java-ee-specifications-jakarta-ee/index.md
> Adding new announcements

- content/news/community-news/2019-03-18-2019-jakarta-ee-8-status/index.md
- content/news/community-news/2019-03-26-2019-jakarta-ee-9-2019-outlook/index.md
- content/news/community-news/2019-03-27-2019-integration-testing-with-testcontainers/index.md
- content/news/community-news/2019-04-02-2019-adopting-jakarta-ee/index.md
- content/news/community-news/2019-04-07-2019-whats-in-a-name/index.md
> #252 - Add new community news

- content/newsletter/index.md
> #254 - Add newsletter

- .github/ISSUE_TEMPLATE/compatibility.md
- config.toml
- content/compatibility/index.md
> #255 - Add compatibility page and issue template

- content/news/community-news/2019-03-07-2019-using-jakarta-eemicroprofile-to-connect-to-apache/index.md
- content/news/community-news/2019-04-12-2019-configuring-microservices-with-microprofile-and-ku/index.md
- content/news/community-news/2019-04-18-2019-red-hat-replaces-oracle-as-openjdk-8-openjdk-11-steward/index.md
- content/news/community-news/2019-04-23-2019-microprofile-jwt-with-keycloak/index.md
- content/news/community-news/2019-04-24-2019-microprofile-and-jakarta-ee/index.md
> #264 - Add new community news

- content/about/jesp/index.md
- layouts/partials/sidebar.html
- package-lock.json
> add Jakarta EE Specification Process

- data/events.yml
- layouts/partials/events.html
> #263 - add new events and update the events partial

- content/news/announcements/2019-05-02-2019-jakarta-ee-community-engagement/index.md
- content/news/announcements/2019-05-03-2019-update-jakarta-ee-rights-java-trademarks/index.md
- content/news/community-news/2019-05-02-microprofile-what-you-need-to-know/index.md
- content/news/community-news/2019-05-03-2019-jakarta-ee-has-landed/index.md
> Add new announcements and community news

- content/news/community-news/2019-05-02-microprofile-what-you-need-to-know/index.md
> #274 - Update community news title

- content/resources/_index.md
Additionally updated existing survey link to use relative rather than
absolute link.
> Please post Dev survey results Afternoon of May 8 #272

- content/news/announcements/2019-05-08-2019-jakarta-ee-community-call/index.md
- content/news/announcements/2019-05-09-2019-new-eclipse-foundation-community-survey/index.md
- content/news/announcements/2019-05-10-2019-cloud-native-imperative/index.md
> #280 - Add new announcements

- layouts/index.html
- layouts/partials/featured_story.html
> #283 - Add results of developer survey in featured story section

- layouts/index.html
> Fix css version for featured story block

- content/news/announcements/2019-05-21-2019-cloud-native-java-innovation-eclipse-foundation/index.md
- content/news/announcements/2019-05-21-2019-update-jakarta-ee-community-may-2019/index.md
- content/news/community-news/2019-05-17-2019-jakarta-ee-and-package-renaming/index.md
> Add new community news and accouncements

- content/news/announcements/2019-05-24-2019-election-time-jakarta-ee-working-group-committees/index.md
- content/news/community-news/2019-05-18-update-jakarta-ee-community-may-2019/index.md
- content/news/community-news/2019-05-22-eclipse-survey/index.md
- content/news/community-news/2019-05-22-jakarta-ee-and-docker-what-you-should-know/index.md
- content/news/community-news/2019-05-27-jakarta-ee-without-javax-world-wont-end/index.md
- package-lock.json
- package.json
> #290 #291 - Add new news items

- content/_index.md
- layouts/index.html
> Fix layout home page

- content/news/community-news/2019-05-14-jakarta-ee-clean-slate/index.md
> #291 - Add community news

- content/meeting_minutes/_index.md
- data/meeting_minutes.yml
- layouts/membership/section.html
> Fix meeting minutes page

- data/events.yml
> #300 - Add new event for Eclipse DemoCamp Florence 2019

- content/legal/trademark_guidelines/index.md
Added paragraph describing brand usage + link to brand usage handbook.
Change-Id: I76b917e0f73d3f3ddfebf630d99c4e7637d45a04
> Please add Brand Usage Handbook to this page at the bottom: ... #303

- content/newsletter/index.md
Updated newsletter page to fix typo and add new newsletter item.
Change-Id: Ifc857fd8527db7d44ecb5fc64a2948ad41bcad96
> Newsletter page updates #305

- content/news/announcements/2019-06-20-update-for-jakarta-ee-community/index.md
Change-Id: I5a529f25f77f01d926418c5c1150b559d939c5e7
> Please add new announcement:... #317

- config.toml
- content/compatibility/index.md
- package-lock.json
Change-Id: I705c94f538a1f7fb62cfe75eb0bb406c752269cc
> Unpublish compatibility page #313

- data/events.yml
Change-Id: Idbe42cd03a4d0f71870b54154d318f5677cb6c70
> Please add new event items and remove GOTO Amsterdam #314

- content/news/community-news/2019-06-17-eclipsecon-europe-call-for-papers-open/index.md
- content/news/community-news/2019-06-17-jcp-copyright-licensing-request/index.md
Change-Id: I6b01c2d1e4da7f6a823c93eb702e0ec8d1485a24
> Please add 2 news items below to annoucements #315

- .travis.yml
- README.md
- package-lock.json
- package.json
> use node_js with travis-ci to support latest version of npm

- content/news/community-news/2019-07-03-j4k-conference/index.md
Change-Id: Iac714a83ba9de2c78c1baace46cf4517c9ee8244
> Please add to community news #340

- package-lock.json
- package.json
Updated the hugo-solstice-theme version.
Change-Id: Iee01dbc98d7b03f12143795e2e6dbd98aa5d9188
> Remove Google + from the website #339

- content/news/announcements/2019-07-15-update-for-jakarta-ee-community/index.md
Added the new announcement.
Change-Id: I96c899f9de285f0c8bac7f70be5df8c73caa077e
> please add to announcements: https://blogs.eclipse.org/post/... #354

- .gitignore
- package.json
> Define the means by which we promote Final Specifications #302

- content/about/_index.md
Added tabs containing committee members to the about page.
Change-Id: I8f5dbb61266794f4e893f0c6235e310fe1889969
> Publishing Jakarta EE Working Group Committee Members #362

- package-lock.json
- package.json
Update the solstice-theme plugin version.
Change-Id: If7776c808c22949874f8868a5e95633a80958dca
> Update the picture in our header #219

- layouts/partials/events.html
Made buttons ~40% wider.
Change-Id: Icf92c4154625b8e6d7f8505265c7a3e8528de826
> Text in event button is too big #372

- content/about/faq/index.md
Added new FAQ entry.
Change-Id: If86e861186e3b8cd436772cb695930c60ccc71b8
> Adding another FAQ item to jakarta.ee FAQ / Jakarta EE ... #381

- .github/ISSUE_TEMPLATE/compatibility.md
Updated the compatibility issue template.
Change-Id: I0ca65e45b6aacb7db60f0580b178faa33e2bd8b4
> Creating a "GitHub Issue" template for those who want to get... #379

- content/about/faq/index.md
Updated link in new FAQ section.
Change-Id: Ie2edc3757b0d17fff8766aaf044d0e105ee2e5af
> Adding another FAQ item to jakarta.ee FAQ / Jakarta EE... #381

- content/compatibility/index.md
Updated the compatible Products page.
Change-Id: I42633739387d3684678ced56addc3e16e8a229ee
> Developing the "Compatible Products" page #389

- config.toml
Added the new compatibility page to the main menu on the site nav.
Change-Id: I035adbf992e288d14e41228f2834ff7e448296e5
> Adding the "Compatible Products" button on the main bar #390

- content/legal/trademark_guidelines/index.md
Updated link text for trademark guidelines.
Change-Id: Ibdd67bea8119020df6d6354bdceca391e9b43e47
> Update the name of "Jakarta EE Trademark License" to "Jakarta EE...#394

- content/compatibility/get_listed/_index.md
> Update get listed pages Jakarta EE link text

- content/news/community-news/2019-06-26-jakarta-ee-39-projects-where-they-are-at/index.md
- content/news/community-news/2019-08-02-how-to-develop-open-liberty-microservices-openshift/index.md
- content/news/community-news/2019-08-07-why-you-should-attend-jakartaone-livestream/index.md
- content/news/community-news/2019-08-08-die-zukunft-von-cloud-native-java/index.md
- content/news/community-news/2019-08-13-eclipse-microprofile-white-paper/index.md
Added 5 new community news articles.
Change-Id: Ie7945d6cec9ac7ad3d833b53a400af40287795dc
> Add to Community News #399

- .gitignore
- build.sh
- package.json
> Move specification html files to static folder

- content/compatibility/get_listed/_index.md
- content/legal/trademark_guidelines/index.md
Updated link to hellosign for trademark license link.
Change-Id: Ibfe24cc6fe8f481f7b68a58ea624786062415a82
> Updating the link of Jakarta EE Trademark license in the 'Jakarta.. #385

- package-lock.json
- package.json
Updated Hugo theme to include new changes for table class injection.
Change-Id: Ia967b5aff3c70cc1bc193e69113faa995744efad
> Fix HTML tables #365

- .travis.yml
- package-lock.json
- package.json
> Hugo downgrade

- content/compatibility/get_listed/_index.md
Updated header of page, changed button order
Change-Id: Id7a96e6eebb226b15c2fef14058c10b3e4a61075
> Developing the "Get Listed" page #388

- content/about/jesp/index.md
Updated link for EFSP
Change-Id: Ib0fed373a0c6e087292bed223e04a7e376d9103e
> Link to EFSP v1.2 on https://jakarta.ee/about/jesp/ #415

- layouts/specifications/list.html
> Fix summary on specification pages

- .travis.yml
- package.json
> make sure that netlify builds are not indexed

- content/connect/index.md
Added Get social section to page.
Change-Id: If680d3bacaa50af6706f6f84af0109dce8b4af3d
> Add a 'Get Social' section to the Connect page #436

- content/compatibility/_index.md
- data/compatible_products.yml
- layouts/shortcodes/compatible_products.html
Prototype of the compatible products mock up
Change-Id: I84fddaab8f0c8753ebc9f9894ca8b71537d95402
> Create prototype of a compatible product #428

- .github/ISSUE_TEMPLATE/compatibility.md
Change-Id: I3f2739f6b77ab2995319852f8635911dd8afee19
> changes in "GitHub issue template" in Get Listed page #438

- config.toml
> Add "releases" CFA in header of every page #432

- less/styles.less
> Fix alignement of Release page's title

- content/about/_index.md
Update council membership based on employment status change.
> Update council membership.

- .github/ISSUE_TEMPLATE/compatibility.md
> Compatible product request must explicitly state the profile #454

- content/news/announcements/2019-09-09-2019-update-jakarta-ee-community-september-2019/index.md
- content/news/announcements/2019-09-10-welcome-future-cloud-native-java/index.md
Added 2 announcements
Change-Id: I64cc3e3df7366bcacc70255f524400c6a31be8c6
> Add to annoucements #459

- content/news/community-news/2019-09-10-eclipse-foundation-delivers-on-jakarta-ee-promise/index.md
- content/news/community-news/2019-09-10-eclipse-foundation-releases-jakarta-ee-8-specifications/index.md
- content/news/community-news/2019-09-10-eclipse-jakarta-ee-arrives/index.md
- content/news/community-news/2019-09-10-jakarta-ee-8-enterprise-java/index.md
- content/news/community-news/2019-09-10-jakarta-ee-8-release-the-future-is-now/index.md
- content/news/community-news/2019-09-10-jakarta-ee-operates-under-open-community-process/index.md
- content/news/community-news/2019-09-10-java-ee-move-to-eclipse-foundation-cloud-native-java/index.md
- content/news/community-news/2019-09-10-java-goes-all-in-jakarta-ee-8-release/index.md
- content/news/community-news/2019-09-10-java-spec-jakarta/index.md
- content/news/community-news/2019-09-10-open-source-enterprise-java-jakarta-ee-8-launches/index.md
Added 10 news items
Change-Id: I3b310390a331446d87c6c98a13eb337d96aa199b
> Add news items to community news #458

- content/news/announcements/2019-09-10-the-eclipse-foundation-releases-jakarta-ee-8/index.md
> Infra 3407 - Add news item for Jakarta EE 8

- data/featuredstory.yml
Removed e-book and JakartaOne stories, and added Jakarta EE 8 to footer.
Updated Jakarta EE 8 body text.
Change-Id: Ifc2b10d1507f259ee58424c95e9bffacb10603e2
> Update the footer & header featured stories #470

- content/_index.md
Replace stay connect with specification on homepage while we work on a
new main-menu.
> Make specification index pages easier to find #457

- content/about/_index.md
- content/membership/members.md
- data/membership/testimonials/bruno_borges.yml
- layouts/membership/section.html
Removed Microsoft from Join Us blurb, and member logo.
Change-Id: If1ec277adaabf68ec43f42a8d766b4c1d7127f46
> Remove Microsoft from jakarta.ee #472

- data/compatible_products.yml
- layouts/shortcodes/compatible_products.html
Signed-off-by: Christopher Guindon <chrisguindon84@gmail.com>
> Link to requests from compatible products page #475

- config.toml
- package-lock.json
- package.json
Updated hugo theme, updated config to include new `hide_cfa_same_page`
configuration setting.
Change-Id: Id5191c3062ccd6b0988f3f88773bdcf9129c43dc
> Please remove "releases" button from https://jakarta.ee/release/ #479

- layouts/release/section.html
> #486 - Add videos to release page

- layouts/release/section.html
> Update the url of the Release videos

- data/events.yml
- data/featuredstory.yml
Change-Id: I32453929a53fd2b3a3908f755b46a298dd74b8fc
> Please add events to event list #489

- content/news/announcements/2019-10-09-payara-server-jakarta-ee-8-compatible/index.md
Change-Id: Ib97d838a63dac0193bfd8d352ef5045f728acb8a
> Posting Payara's press release on Jakarta.ee Announcement section #497

- layouts/shortcodes/compatible_products.html
Added sort to compatible products.
Change-Id: Iadae85602852d37918da9c98ae07bd01b9e37f9b
> Compatible Products should be listed alphabetical #496

- data/membership/testimonials/david_blevins.yml
Added David Blevins quote
Change-Id: I773a2d380ceb1b1e1685bff4b7d879718248dae4
> Adding a quote in the https://jakarta.ee/membership/ #506

- content/news/announcements/2019-09-17-eclipse-foundation-wins-dukes-choice-award/index.md
- data/events.yml
Includes changes for #514
Change-Id: I5052bb6ccd3560fa024f98f567698f3dd0277cc3
> Add to announcements #513

- config.toml
- content/resources/_index.md
Weight 0 doesn't seem to work so I moved Blog to 8 in order to keep its current position.
> Added link to documentation

- content/resources/_index.md
> Link to Developer Survey Landing Page #522

- content/news/announcements/2019-11-06-election-updates-fall-2019/index.md
> Adding the bulletin announcement under Jakarta.ee announcement #523

- content/news/announcements/2019-12-03-jakarta-ee-call-update-december-2019/index.md
- content/news/announcements/2019-12-31-jakarta-ee-call-update-january-2020/index.md
- content/news/announcements/2020-02-04-jakarta-ee-call-update-february-2020/index.md
- content/news/announcements/2020-03-03-jakarta-ee-call-update-march-2020/index.md
- content/news/announcements/2020-03-31-jakarta-ee-call-update-april-2020/index.md
- content/news/announcements/2020-05-05-jakarta-ee-call-update-may-2020/index.md
- content/news/announcements/2020-06-02-jakarta-ee-call-update-june-2020/index.md
- content/news/announcements/2020-07-01-jakarta-ee-call-update-july-2020/index.md
- content/news/announcements/2020-08-04-jakarta-ee-call-update-august-2020/index.md
- content/news/announcements/2020-09-01-jakarta-ee-call-update-september-2020/index.md
- content/news/announcements/2020-10-06-jakarta-ee-call-update-october-2020/index.md
- content/news/announcements/2020-11-03-jakarta-ee-call-update-november-2020/index.md
- content/news/announcements/2020-12-01-jakarta-ee-call-update-december-2020/index.md
> Feature The Jakarta EE monthly update call under Jakarta.ee,... #531

- content/connect/index.md
> Add a section for Jakarta EE Monthly Update Calls in Jakarta.ee/... #532

- content/about/_index.md
Signed-off-by: CesarHernandezGt <chernandez@tomitribe.com>
> Updated Tomitribe alternate.

- content/resources/_index.md
> Adding the link to presentations in the Jakarta EE slideshare in... #540

- content/newsletter/index.md
> Add the latest Jakarta EE newsletters to ... #541

- .gitignore
- content/news/announcements/2019-12-04-jakarta-tech-talk/index.md
> Add Jakarta Tech Talk under Announcements #546

- data/events.yml
> Add under Events #551

- content/about/_index.md
Signed-off-by: Jean-Louis Monteiro <jeanouii@gmail.com>
> Add JL Monteiro as a specification committee alternate

- content/news/announcements/2019-12-31-jakarta-ee-call-update-january-2020/index.md
- content/news/announcements/2020-01-07-jakarta-ee-call-update-january-2020/index.md
> #531 - Update scheduled january 15th annoncement

- content/news/community-news/2019-12-07-kickstart-a-jakarta-ee-8-application/index.md
> #556 - Add Community News

- data/featuredstory.yml
> #559 - Update featured story text

- content/news/announcements/2020-01-07-jakarta-ee-call-update-january-2020/index.md
> Updated January community call announcement release date

- content/about/_index.md
> Update specification committee list on about page

- layouts/membership/section.html
- layouts/partials/sidebar.html
> Remove leftover Registered marks

- data/events.yml
> Add CN4J Day to Events #580

- data/featuredstory.yml
> Change Copy of Banner in Jakarta.ee #581

- layouts/shortcodes/pages/compatibility-products.html
- package.json
> Fix get listed page

- content/commitees/specification/operations.md
- content/committees/specification/operations.md
> Add the specification committee operations doc

- content/news/announcements/2020-01-16-moving-forward-with-jakarta-ee-9/index.md
> Add Article to Announcement section #595

- content/committees/marketing/_index.md
- content/committees/specification/_index.md
- content/committees/steering/_index.md
Need a Committees index page with navigation #597
> include Committee in title

- content/news/announcements/2020-01-28-cn4j-day/index.md
> #610 - Add a new announcement

- content/news/announcements/2020-01-28-cn4j-day/index.md
> Update CN4J accouncement

- .travis.yml
- README.md
- package.json
Temporary fix until we have time to fix the shell script or move
this content.
> npm install fails on windows #620

- layouts/shortcodes/pages/connect.html
> Add link to Jakarta Development Slack

- layouts/committees/list.html
> Add Documents heading to All Cmte pages

- layouts/committees/list-landing-page.html
- layouts/committees/list.html
> Order committees by name #638

- content/committees/specification/operations/index.md
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>
> Update ops guide per experience with javase PRs

- README.md
> Explain the current situation and the use of "src" instead of "master"

- layouts/shortcodes/pages/membership/explore-members.html
Updated Primeton to be in new Enterprise members section
> Add Primeton Information Technologies logo on the Jakarta EE... #636

- config.toml
- content/community/_index.md
- content/community/adopt-a-spec/index.md
- data/spec_adopters.yml
- layouts/specifications/list.html
> Adopt-A-Spec for JUGs #616

- content/news/announcements/2020-03-03-jakarta-ee-call-update-march-2020/index.md
- content/news/announcements/2020-03-10-jakarta-ee-call-update-march-2020/index.md
> Update the post scheduled for announcement section #646

- package-lock.json
- package.json
The Jakarta EE 8 announcement under Jakarta.ee announcement section
seems broken #650
> Fix external news item links on sub-pages

- data/events.yml
> Update Events on Jakarta.ee #667

- content/committees/steering/brand_use_by_projects.md
The Jakarta EE Steering Committee approved this policy today.
> Proper use of the Jakarta Brand by Eclipse Projects

- layouts/specifications/list.html
> Change link text from Website to Project and update icon

- layouts/shortcodes/about-committee-members.html
> Primeton committee  update

- layouts/shortcodes/pages/connect.html
> Update slack link

- content/community/adopt-a-spec/index.md
- layouts/shortcodes/jug-adopters-list.html
> Adding JUGs logos on the "Adopt a Spec" page #669

- layouts/shortcodes/about-committee-members.html
> Update on jakarta.ee/committees -> Committee Members  Primeton indicating they are  elected Enterprise members

- content/_index.md
- less/styles.less
- package-lock.json
- package.json
> The ® could be more decent on the Jakarta.ee frontpage #706

- content/news/announcements/2020-04-07-add-your-voice-2020-jakarta-ee-developer-survey/index.md
> Add Mike's blog to announcements section on Jakarta.ee #709

- content/schemas/_index.md
- content/xml/_index.md
- content/xml/ns/_index.md
- content/xml/ns/jakartaee/_index.md
- content/xml/ns/jaxb/_index.md
- content/xml/ns/jaxws/_index.md
- content/xml/ns/persistence/_index.md
- data/jakartaee_schemas.yml
- data/jaxb_schemas.yml
- data/jaxws_schemas.yml
- data/persistence_schemas.yml
- layouts/shortcodes/schemas/content.html
- layouts/shortcodes/schemas/jakartaee-list.html
- layouts/shortcodes/schemas/jaxb-list.html
- layouts/shortcodes/schemas/jaxws-list.html
- layouts/shortcodes/schemas/persistence-list.html
> Reorganize schemas

- data/events.yml
> Update the event section on Jakarta.ee (#714)

- data/persistence_schemas.yml
> Update name for Persistence API schemas

- data/jakartaee_schemas.yml
- layouts/shortcodes/schemas/jakartaee-list.html
> Add refs to dependent namespaces

- content/xml/ns/jakartaee/_index.md
> Fix link to Jakarta EE 89 schemas

- data/events.yml
> Please add JakartaOne Livestream CN4J under Jakarta.ee event ...#720

- layouts/shortcodes/meeting-minutes-single.html
> Jakarta EE WG committees' meeting min not available #728

- content/committees/marketing/_index.md
- content/committees/specification/_index.md
- content/committees/steering/_index.md
> Updating committees' members

- content/committees/specification/operations/index.md
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>
> Internal doc links were not working

- content/committees/specification/_index.md
- layouts/committees/list.html
> Reorder content of pages to put Docs on top

- data/featuredstory.yml
> Add JakartaOne Livestream Cloud Native Banner Rotation #724

- content/committees/marketing/_index.md
- content/committees/specification/_index.md
- content/committees/steering/_index.md
Add Eric QingYu Mengas contact for Primeton, and spelling correction on other committees members pages
> Update committees members

- content/news/announcements/2019-05-08-2019-jakarta-ee-community-call/index.md
> The upcoming Jakarta EE Community call on 13 May is cancelled... #739

- data/jakartaee_schemas.yml
- static/xml/ns/jakartaee/application-client_9.xsd
- static/xml/ns/jakartaee/application_9.xsd
- static/xml/ns/jakartaee/connector_2_0.xsd
- static/xml/ns/jakartaee/ejb-jar_4_0.xsd
- static/xml/ns/jakartaee/jakartaee_9.xsd
- static/xml/ns/jakartaee/jakartaee_web_services_2_0.xsd
- static/xml/ns/jakartaee/jakartaee_web_services_client_2_0.xsd
- static/xml/ns/jakartaee/permissions_9.xsd
- static/xml/ns/jakartaee/web-app_5_0.xsd
- static/xml/ns/jakartaee/web-common_5_0.xsd
- static/xml/ns/jakartaee/web-facelettaglibrary_3_0.xsd
- static/xml/ns/jakartaee/web-facesconfig_3_0.xsd
- static/xml/ns/jakartaee/web-fragment_5_0.xsd
- static/xml/ns/jakartaee/web-partialresponse_3_0.xsd
Signed-off-by: Ivan St. Ivanov <ivan.st.ivanov@gmail.com>
> Add the schemas for the remaining Jakarta EE 9 descriptors

- data/featuredstory.yml
> Extending the deadline for the 2020 Jakarta EE developer survey ...#745

- data/featuredstory.yml
> Extending the deadline for the 2020 Jakarta EE developer survey... #745

- layouts/shortcodes/jug-adopters-list.html
- layouts/specifications/list.html
- less/styles.less
Change-Id: I6762fa309fa501cf893f53ce17628cd3bd20067a
> Shrink the size of the adopter logos

- content/community/adopt-a-spec/index.md
> Move list of adopters to top of page

- config.toml
> Add link to starter from resource

- data/featuredstory.yml
> Update the Jakarta EE banner and footer #761

- content/committees/marketing/_index.md
Signed-off-by: CesarHernandezGt <chernandez@tomitribe.com>
> Updated Tomitribe marketing committee _index.md.

- layouts/shortcodes/pages/membership/explore-members.html
> Change from Participating to Participant Members on the Explore Members

- data/events.yml
> Adding JNation 2020 to the events page

- data/meeting_minutes.yml
- layouts/shortcodes/meeting-minutes-single.html
- layouts/shortcodes/meeting_minutes.html
- less/styles.less
- package-lock.json
- package.json
> Tabular view of the Jakarta EE committees meeting minutes per year #726

- data/events.yml
> Update Events on Jakarta.ee #770

- data/featuredstory.yml
> Update the Jakarta EE banner #767

- data/spec_adopters.yml
Signed-off-by: Daniel Dias <daniel.dias.analistati@gmail.com>
> add soujava a adopter to mvc

- data/featuredstory.yml
> Add banner to banner rotation on Jakarta.EE #775

- config.toml
> Add link to community drive to Resources menu item. Close #782

- config.toml
> Add link to YouTube Channel from Resources menu. Closes #780

- package-lock.json
- package.json
> Add non-official support for Hugo 0.71.1

- content/committees/marketing/_index.md
> Adding John Clingan as member of MKT committee

- content/news/community-news/2020-06-05-the-top-25-greatest-java-apps-ever-written/index.md
Fix #796
Change-Id: I54eefb29a5fd86bc5d87116a44b2487d8109c549
> Add community news: top 25 Java apps #796

- static/xml/ns/jakartaee/web-facesconfig_3_0.xsd
- static/xml/ns/jakartaee/web-jsptaglibrary_3_0.xsd
> Update schemas with javax->jakarta changes

- static/xml/ns/jakartaee/jsp_3_0.xsd
> Incorrect targetNamespace in jsp_3_0.xsd

- static/xml/ns/jakartaee/web-app_5_0.xsd
- static/xml/ns/jakartaee/web-jsptaglibrary_3_0.xsd
Incorporates changes from https://github.com/eclipse-ee4j/jakartaee-schemas/pull/11
> updated schemas for web-app and web-jsptaglibrary

- data/events.yml
> Add Event to Jakarta.ee #808

- content/about/_index.md
> About page fix

- content/schemas/_index.md
- content/xml/ns/_index.md
- content/xml/ns/jakartaee/_index.md
- content/xml/ns/validation/_index.md
- data/jakartaee_schemas.yml
- data/validation_schemas.yml
- layouts/shortcodes/schemas/validation-list.html
- static/xml/ns/validation/validation-configuration-3.0.xsd
- static/xml/ns/validation/validation-mapping-3.0.xsd
Signed-off-by: Scott M Stark <starksm64@gmail.com>
> Add the Jakarta Bean Validation schema files to the website

- config.toml
> Add link to JakartaOne Livestream under resources

- static/xml/ns/jakartaee/jobXML_2_0.xsd
Signed-off-by: Scott Kurz <skurz@us.ibm.com>
My apologies... small bug here.    I wanted to make sure you were OK with the change but I should have just asked you to review the draft before testing.
Anyway, this should fix it.
> Correct batch jobXML xsd schema prefix

- layouts/partials/head_custom.html
- package-lock.json
- package.json
Change-Id: I182c2358d723db63fb67c478846d4663e9e43146
> Use open sans google font

- layouts/shortcodes/pages/newsletter.html
Change-Id: I8f452090131e4c2132fbf927bdf0354bc4ab750d
> Bug 3814 - Update the Jakarta EE Newsletter Archives

- content/resources/_index.md
> [ Jakarta EE Resources Tab] Add Friends of Jakarta link #835

- config.toml
> Add Friends of Jakarta EE to the megamenu #835

- layouts/specifications/list.html
- less/styles.less
> Fix #572 - Improve the layout of the specifications pages

- content/committees/specification/_index.md
> Adding Marcelo as Elected Participant Member Representative

- data/compatible_products.yml
> Open Liberty 20.0.0.3 as a Compatible Software Product for...#855

- static/xml/ns/persistence/orm/orm_3_0.xsd
"publish" the fix for https://github.com/eclipse-ee4j/jpa-api/issues/286
> adopt latest orm xsd

- layouts/shortcodes/pages/mailing-lists.html
> remove JTS from mailing list

- package-lock.json
- package.json
> Update Hugo version to Fix IE JS

- package-lock.json
- package.json
> IE fix for featured story/footer

- data/compatible_products.yml
> update payara version

- layouts/partials/footer_custom.html
> add form for subscribe

- .travis.yml
- README.md
- netlify.toml
- package-lock.json
- package.json
> update to Hugo 0.76.5

- content/resources/_index.md
- content/resources/_index.zh.md
Fix #932 
Hi Eric, @laliwa ,
I'm not sure if my translation is professional  😅 Would you mind helping me review? Thanks!
> Add tech talk sign up form #932

- layouts/shortcodes/pages/jakartaeechina/index.html
Signed-off-by: laliwa <40311795@qq.com>
> change link to eclipse.org mailing list sign-up

- package-lock.json
- package.json
> update base theme

- content/membership/_index.md
> add spacing for mobile view #943

- layouts/release/9/section.html
According to https://github.com/jakartaee/jakarta.ee/pull/929#issuecomment-726874901
> drop plural

- layouts/shortcodes/pages/release/9.html
- less/release-9.less
- less/styles.less
- square off card corners
- tweak card shadows
- make feature cards same height if in one line
- tweaked hr and br styles
Signed-off-by: Andrii Malytskyi <amalytskyi@tomitribe.com>
> Release 9 page visual tweks

- layouts/specifications/list.html
> Change specifications order, first weight, second alpha #947

- data/compatible_products.yml
- i18n/en.toml
- i18n/zh.toml
- layouts/shortcodes/pages/compatibility-products.html
- package.json
Fix #878 
Before merging, what contents do we need for Jakarta EE 9? @chrisguindon 
> phase two - Compatible Products Page Design #878

- layouts/shortcodes/pages/release/9.html
- less/release-9.less
Fix #1001 
Note: Before merging, let me confirm with Karen if there is any preferred design for it
> Add video #1001

- content/compatibility/_index.zh.md
- content/connect/_index.zh.md
- content/resources/_index.zh.md
- i18n/en.toml
- i18n/zh.toml
- layouts/shortcodes/pages/connect.html
Fix #1008 
Hi @laliwa Eric, do you think this translation needs to be updated for this minor title change? Thanks!
> update Connect page title and remove some page_title in Chinese to be consistent with Eng page

- data/compatible_products.yml
> Update Payara version to 5.23.0 and add to web profile #1005 

- static/_redirects
> create a redirect for jakarta 9

- data/compatible_products.yml
> Add GlassFish for jakartaee 9 compatible products

- layouts/release/9/section.html
- less/release-9.less
> remove upcoming text #1022

- content/compatibility/_index.md
- content/compatibility/_index.zh.md
- content/compatibility/download/_index.md
- content/compatibility/download/_index.zh.md
- data/compatible_products.yml
- i18n/en.toml
- i18n/zh.toml
- layouts/compatibility/download/section.html
- layouts/shortcodes/pages/compatibility-products-download.html
- layouts/shortcodes/pages/compatibility-products-header.html
- layouts/shortcodes/pages/compatibility-products.html
- less/styles.less
> Update Jakarta EE Compatibility Page #1013

- data/meeting_minutes.yml
Part of #1029 
For the https://jakarta.ee/committees/specification/operations/names.xml, we need help from Ivar. Other than that, the fix for the PDF can be ready.
> Fix broken links on jakarta.ee #1029

- layouts/shortcodes/events.html
- package-lock.json
- package.json
The theme is fixed. Should be good to add this classname.
> fix event button space on mobile

- layouts/shortcodes/pages/compatibility-products-download.html
- layouts/shortcodes/pages/compatibility-products.html
Signed-off-by: Thiago Henrique Hupner <thihup@gmail.com>
> Fix Github URL

- content/committees/specification/operations/index.md
> update project names and codes link #1029 
